import datetime as _dt
from zoneinfo import ZoneInfo
from ..config import REPORT_TIMEZONE

TZ = ZoneInfo(REPORT_TIMEZONE)

def format_us_date(date: _dt.date | None = None) -> str:
    """
    Return the date formatted in US style 'Month Day, Year'.
    If no date is passed, use today's date in the configured timezone.
    """
    if date is None:
        date = _dt.datetime.now(tz=TZ).date()
    return date.strftime("%B %d, %Y")

def us_datetime(now: _dt.datetime | None = None) -> str:
    """
    Return 'Month DD, YYYY HH:MM AM/PM' in US style,
    with timezone from config.REPORT_TIMEZONE.
    """
    now = now or _dt.datetime.now(tz=TZ)
    return now.strftime("%B %d, %Y %I:%M %p")

def branding_line(version: str, now: _dt.datetime | None = None) -> str:
    """
    Build the standard one-line branding string for headers.
    """
    return f"This digest was generated by the Humanitarian AI Agent v{version} at {us_datetime(now)}"
